[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    adafruit/Adafruit SSD1306 @ ^2.5.7
    adafruit/Adafruit GFX Library
    fastled/FastLED
    https://github.com/crankyoldgit/IRremoteESP8266.git   ; or the Library Manager name
; uECC - add as git dependency or put in lib/ folder
    https://github.com/kmackay/micro-ecc.git   ; adjust if needed

build_flags =
    -D CORE_DEBUG_LEVEL=1
    -D LT_DEBUG=1
    -D LT_DEBUGGER_NODE=0
    -D LT_REQUIRED_READY=2

[env:esp32debugger]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    adafruit/Adafruit SSD1306 @ ^2.5.7
    adafruit/Adafruit GFX Library
    fastled/FastLED
    https://github.com/crankyoldgit/IRremoteESP8266.git
    https://github.com/kmackay/micro-ecc.git

build_flags =
    -D CORE_DEBUG_LEVEL=1
    -D LT_DEBUG=1
    -D LT_DEBUGGER_NODE=1
    -D LT_REQUIRED_READY=2
